select * from customer limit 20;

-- Q1: what is the total revenue generated by male and female customers?
select "Gender", sum("Purchase Amount (USD)") as revenue
from customer
group by "Gender";

--Q2: Which customer used a discount but still spent more than than the average puchase amount?
select "Customer ID", "Purchase Amount (USD)"
from customer
where "Discount Applied" = 'Yes'
  and "Purchase Amount (USD)" >= (select avg("Purchase Amount (USD)") from customer);

--Q3: Which are the top 5 product  with the highest average review rating?
select "Item Purchased", round(avg("Review Rating")::numeric, 2) as "Average Product Rating"
from customer
group by "Item Purchased"
order by avg("Review Rating") desc
limit 5;

--Q4: Compare the average Puchase Amount between Standerd and Express Shipping?
select "Shipping Type",
       round(avg("Purchase Amount (USD)")::numeric, 2) as "Average Purchase Amount"
from customer
where "Shipping Type" in ('Standard', 'Express')
group by "Shipping Type";

--Q5: Do subscribe customer spend more? Comapre average spend and total revenue between subscribe and non-subscribe

select "Subscription Status",
       count("Customer ID") as total_customer,
       round(avg("Purchase Amount (USD)")::numeric, 2) as avg_spend,
       round(sum("Purchase Amount (USD)")::numeric, 2) as total_revenue
from customer
group by "Subscription Status"
order by total_revenue desc, avg_spend desc;

--Q6: which 5 product have the hightest percentage of purchase with discount applied?

select "Item Purchased",
       round(100.0 * count(*) filter (where "Discount Applied" = 'Yes') / count(*), 2) as discount_percentage
from customer
group by "Item Purchased"
order by discount_percentage desc
limit 5;

--Q7: segment customer into New, Returning, and Loyed based on their total number of 
-- previous purchase, and show the count of each segment 
with customer_type as (
    select "Customer ID",
           "Previous Purchases",
           case
               when "Previous Purchases" = 1 then 'New'
               when "Previous Purchases" between 2 and 10 then 'Returning'
               else 'Loyal'
           end as customer_segment
    from customer
)
select customer_segment,
       count(*) as "Number of Customers"
from customer_type
group by customer_segment
order by "Number of Customers" desc;

--Q8: What are the top 3 most purchase product within each category?

with item_counts as (
    select "Category",
           "Item Purchased",
           count("Customer ID") as total_orders,
           row_number() over (
               partition by "Category"
               order by count("Customer ID") desc
           ) as item_rank
    from customer
    group by "Category", "Item Purchased"
)
select item_rank,
       "Category",
       "Item Purchased",
       total_orders
from item_counts
where item_rank <= 3
order by "Category", item_rank;

--Q9: Are customer who are report buyers(more than 5 previous purchase) also likely to subscribe?
select case
           when "Previous Purchases" > 5 then 'Repeat Buyer (>5)'
           else 'Not Repeat Buyer (<=5)'
       end as buyer_type,
       count(*) as total_customers,
       count(*) filter (where "Subscription Status" = 'Yes') as subscribers,
       round(100.0 * count(*) filter (where "Subscription Status" = 'Yes') / count(*), 2) as pct_subscribed
from customer
group by 1
order by pct_subscribed desc;

--Q10: what is the revenue contribution of each age group?
select case
           when "Age" between 18 and 25 then '18-25'
           when "Age" between 26 and 35 then '26-35'
           when "Age" between 36 and 45 then '36-45'
           when "Age" between 46 and 55 then '46-55'
           when "Age" between 56 and 65 then '56-65'
           else '66+'
       end as age_group,
       sum("Purchase Amount (USD)") as total_revenue,
       round(100.0 * sum("Purchase Amount (USD)") / sum(sum("Purchase Amount (USD)")) over (), 2) as revenue_pct
from customer
group by 1
order by total_revenue desc;


